[package]
name = "aoc_15"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.10.0"
hex-literal = "0.3.4"
hex = "0.4.3"